import os
#COMPUTER_NAME = os.environ['COMPUTERNAME']
#print("Computer: ", COMPUTER_NAME)

TARGET_VOXEL_MM = 1.00
MEAN_PIXEL_VALUE_NODULE = 41
LUNA_SUBSET_START_INDEX = 0
LUNA_SUBSET_END_INDEX = 5
TIANCHI_SUBSET_START_INDEX = 0
TIANCHI_SUBSET_END_INDEX = 5
SEGMENTER_IMG_SIZE = 320

BASE_DIR_SSD = "/home/zico/deepluna/"
BASE_DIR = "/home/zico/deepluna/"
EXTRA_DATA_DIR = BASE_DIR + "resources/"
TIANCHI_RAW_SRC_DIR = BASE_DIR + "tianchi/"
LUNA16_RAW_SRC_DIR = BASE_DIR + "luna16/"

LUNA16_EXTRACTED_IMAGE_DIR = LUNA16_RAW_SRC_DIR + "extracted_images_test2/"
#TIANCHI_EXTRACTED_IMAGE_DIR = TIANCHI_RAW_SRC_DIR + "extracted_images/"
#TIANCHI_NODULE_DETECTION_DIR = TIANCHI_RAW_SRC_DIR + "nodule_predictions/"
TIANCHI_EXTRACTED_IMAGE_DIR = TIANCHI_RAW_SRC_DIR + "extracted_images_test2/"
TIANCHI_NODULE_DETECTION_DIR = TIANCHI_RAW_SRC_DIR + "nodule_predictions_test2/"